const dotenv = require("dotenv");
dotenv.config();

const { createClient } = require("@supabase/supabase-js");
const axios = require("axios");

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);

async function summarizeAndSend() {
  const { data: todos, error } = await supabase
    .from("todos")
    .select("*")
    .eq("status", "pending");

  if (error) {
    throw new Error("Failed to fetch todos");
  }

  if (!todos || todos.length === 0) {
    throw new Error("No pending todos to summarize.");
  }

  const taskList = todos.map((t) => `- ${t.task}`).join("\n");

  const prompt = `
I have the following pending tasks:

${taskList}

Please provide a concise summary of these tasks. Group related items together when possible.
Highlight any urgent or important tasks. The summary should be professional and suitable for sharing with a team.
Also, give an estimated time to complete all these tasks if each task takes about 30 minutes.
`;

  const cohereResponse = await axios.post(
    "https://api.cohere.ai/v1/generate",
    {
      model: "command",
      prompt: prompt,
      max_tokens: 300,
      temperature: 0.7,
    },
    {
      headers: {
        Authorization: `Bearer ${process.env.COHERE_API_KEY}`,
        "Content-Type": "application/json",
      },
    }
  );

  const summary = cohereResponse.data.generations[0].text.trim();

  await axios.post(process.env.SLACK_WEBHOOK_URL, {
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: "Todo Summary",
        },
      },
      {
        type: "divider",
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: summary,
        },
      },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: "Generated by *Todo Summary Assistant*",
          },
        ],
      },
    ],
  });

  return summary;
}

module.exports = summarizeAndSend;
